WTPlanner/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <pluralLabel>Events</pluralLabel>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The event this session is associated with</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The category or type of session (e.g., Booth, Theatre, Trailhead)</description>
    <label>Session Type</label>
    <referenceTo>Session_Type__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session_Type__c/Session_Type__c.object-meta.xml
<CustomObject>
    <label>Session Type</label>
    <pluralLabel>Session Types</pluralLabel>
    <nameField>
        <label>Session Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Session_Type__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>The parent event this session type belongs to (Master-Detail relationship)</description>
    <label>Event</label>
    <type>MasterDetail</type>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Session Types</relationshipLabel>
    <relationshipName>Session_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
</CustomField>

WTPlanner/force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <pluralLabel>Shifts</pluralLabel>
    <nameField>
        <label>Shift Number</label>
        <type>AutoNumber</type>
        <displayFormat>SHIFT-{00000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Shift__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>The session this shift belongs to (Master-Detail relationship)</description>
    <label>Session</label>
    <type>MasterDetail</type>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
</CustomField>

WTPlanner/force-app/main/default/objects/Shift__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Assigned User</label>
    <type>Lookup</type>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

WTPlanner/force-app/main/default/classes/DeleteProtectionHandler.cls
public with sharing class DeleteProtectionHandler {

    public static void preventEventDeletion(List<Event__c> events) {
        Set<Id> eventIds = new Set<Id>();
        for (Event__c evt : events) {
            eventIds.add(evt.Id);
        }

        Set<Id> blockedIds = new Set<Id>();
        for (Shift__c shift : [
            SELECT Session__r.Session_Type__r.Event__c
            FROM Shift__c
            WHERE Session__r.Session_Type__r.Event__c IN :eventIds
              AND User__c != null
        ]) {
            blockedIds.add(shift.Session__r.Session_Type__r.Event__c);
        }

        for (Event__c evt : events) {
            if (blockedIds.contains(evt.Id)) {
                evt.addError('Cannot delete: this event has sessions with assigned shifts. Remove all shift assignments first.');
            }
        }
    }

    public static void preventSessionTypeDeletion(List<Session_Type__c> sessionTypes) {
        Set<Id> stIds = new Set<Id>();
        for (Session_Type__c st : sessionTypes) {
            stIds.add(st.Id);
        }

        Set<Id> blockedIds = new Set<Id>();
        for (Shift__c shift : [
            SELECT Session__r.Session_Type__c
            FROM Shift__c
            WHERE Session__r.Session_Type__c IN :stIds
              AND User__c != null
        ]) {
            blockedIds.add(shift.Session__r.Session_Type__c);
        }

        for (Session_Type__c st : sessionTypes) {
            if (blockedIds.contains(st.Id)) {
                st.addError('Cannot delete: this session type has sessions with assigned shifts. Remove all shift assignments first.');
            }
        }
    }

    public static void preventSessionDeletion(List<Session__c> sessions) {
        Set<Id> sessionIds = new Set<Id>();
        for (Session__c s : sessions) {
            sessionIds.add(s.Id);
        }

        Set<Id> blockedIds = new Set<Id>();
        for (Shift__c shift : [
            SELECT Session__c
            FROM Shift__c
            WHERE Session__c IN :sessionIds
              AND User__c != null
        ]) {
            blockedIds.add(shift.Session__c);
        }

        for (Session__c s : sessions) {
            if (blockedIds.contains(s.Id)) {
                s.addError('Cannot delete: this session has assigned shifts. Remove all shift assignments first.');
            }
        }
    }
}