WTPlanner/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <pluralLabel>Events</pluralLabel>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The event this session is associated with</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Physical location or area where this session takes place</description>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session__c/fields/Max_Shifts__c.field-meta.xml
<CustomField>
    <fullName>Max_Shifts__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Maximum number of staff shifts allowed per time slot for this session</description>
    <label>Max Shifts Allowed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session__c/fields/Min_Shifts__c.field-meta.xml
<CustomField>
    <fullName>Min_Shifts__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Minimum number of staff shifts required per time slot for this session</description>
    <label>Min Shifts Needed</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The category or type of session (e.g., Booth, Theatre, Trailhead)</description>
    <label>Session Type</label>
    <referenceTo>Session_Type__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

WTPlanner/force-app/main/default/objects/Session_Type__c/Session_Type__c.object-meta.xml
<CustomObject>
    <label>Session Type</label>
    <pluralLabel>Session Types</pluralLabel>
    <nameField>
        <label>Session Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Session_Type__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>The parent event this session type belongs to (Master-Detail relationship)</description>
    <label>Event</label>
    <type>MasterDetail</type>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Session Types</relationshipLabel>
    <relationshipName>Session_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
</CustomField>

WTPlanner/force-app/main/default/objects/Shift__c/Shift__c.object-meta.xml
<CustomObject>
    <label>Shift</label>
    <pluralLabel>Shifts</pluralLabel>
    <nameField>
        <label>Shift Number</label>
        <type>AutoNumber</type>
        <displayFormat>SHIFT-{00000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WTPlanner/force-app/main/default/objects/Shift__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
    <required>true</required>
</CustomField>

WTPlanner/force-app/main/default/objects/Shift__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>The session this shift belongs to (Master-Detail relationship)</description>
    <label>Session</label>
    <type>MasterDetail</type>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
</CustomField>

WTPlanner/force-app/main/default/objects/Shift__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
    <required>true</required>
</CustomField>

WTPlanner/force-app/main/default/objects/Shift__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Assigned User</label>
    <type>Lookup</type>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Shifts</relationshipLabel>
    <relationshipName>Shifts</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

WTPlanner/force-app/main/default/classes/StaffingAPI_MyShiftsTest.cls
@isTest
private class StaffingAPI_MyShiftsTest {

    @testSetup
    static void setup() {
        Event__c event = new Event__c(Name = 'Test Event');
        insert event;

        Session_Type__c sessionType = new Session_Type__c(
            Name = 'Theatre',
            Event__c = event.Id
        );
        insert sessionType;

        Session__c session = new Session__c(
            Name = 'Test Session',
            Session_Type__c = sessionType.Id,
            Location__c = 'Main Theatre',
            Min_Shifts__c = 2,
            Max_Shifts__c = 5
        );
        insert session;

        Shift__c shift = new Shift__c(
            Session__c = session.Id,
            Start_Time__c = Time.newInstance(9, 0, 0, 0),
            End_Time__c = Time.newInstance(11, 0, 0, 0),
            User__c = UserInfo.getUserId()
        );
        insert shift;
    }

    @isTest
    static void testGetMyShifts() {
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/staffing/my-shifts';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        StaffingAPI_MyShifts.doGet();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        List<Object> results = (List<Object>) JSON.deserializeUntyped(
            RestContext.response.responseBody.toString()
        );
        System.assertEquals(1, results.size());
    }

    @isTest
    static void testGetMyShifts_NoShifts() {
        Shift__c shift = [SELECT Id FROM Shift__c LIMIT 1];
        shift.User__c = null;
        update shift;

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/staffing/my-shifts';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        StaffingAPI_MyShifts.doGet();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        List<Object> results = (List<Object>) JSON.deserializeUntyped(
            RestContext.response.responseBody.toString()
        );
        System.assertEquals(0, results.size());
    }
}